### PR TITLE
Badfiles plugin

### PR DESCRIPTION
**Pull request by sampsyo**
A new plugin by @fxthomas!

Before merging, I'd love to have input from @fxthomas about whether I messed anything up. I also have a short to-do list:

* [ ] No configuration should be required to use the defaults.
* [ ] The documentation page could still use some reorganization to match the rest of the docs.

### CODE REVIEW

**Comment by fxthomas** [comment]
I checked that it works as expected on my library. Some thoughts and questions :

* Great for the cleanup! I personally have `flake8` set for 90 characters and prefer `%`-interpolation to `format`, but having an official coding style is much more important than my own preferences ;)
* What would you change in the documentation?
* I submitted a small merge request which among others removes the need for configuration to use the defaults and adds color output to make it more readable. If you have thoughts on that, do not hestiate! (Did I use `ui.colorize` correctly?)

**Comment by fxthomas** [comment]
(See #1570 for the PR)

**Comment by fxthomas** [comment]
Also, for some reason `beets.dbcore` crashes on `lib.items(args)` when I try a regexp query, e.g. :

    beet bad title::'^M.*$'

Any idea on why?

_(The one in the docs doesn't actually work either, I was checking it when I found this...)_

**Comment by fxthomas** [comment]
Never mind, looking at other plugins' source I should have used `ui.decargs`, now fixed in the PR!

**Comment by sampsyo** [comment]
Awesome; thanks for the additional changes! And double thanks for acquiescing to the style guide, even if 80 columns seems draconian. :smiley: I've added you as a collaborator now, so feel free to continue changing things if you like.

The documentation actually seems like it's in fine shape; I'm not sure what I was talking about before.

The colorization stuff looks perfect; great work figuring that out!

Thanks again for the contribution.

**Pull request merged**
