### PR TITLE
Use comma as "or" operator for queries

### PR DESCRIPTION
**Pull request by tomjaspers**
Scan the query parts for commas (`u','`) and treat these as (sub) `AndQuery`s
that need to be wrapped in an `OrQuery` (if there are more than one).

Supports `foo, bar` and `foo , bar`. 

See #976

### CODE REVIEW

**Comment by brunal** [comment]
That means that any query holding a comma should now be escaped... I'm not sure how I feel about that.

**Comment by sampsyo** [comment]
Awesome! This looks great to me. As that thread in #976 suggested, a comma seems like the right thing to me. It's not quite true, @brunal, that every comma will need to be escaped—commas are only ORs when they appear by themselves or at the end of a term. So `foo, bar` is an OR query but `foo,bar` is not. In the shell, quotes even behave as expected, so:

    $ beet ls "foo, bar"

does not invoke an OR query.

I'm inclined to merge this now. We *could* restrict this to only work with separated commas (`foo , bar`), but I'm inclined to say that this is less surprising as-is.

**Comment by tomjaspers** [comment]
@sampso My original implementation only worked with separated commas, but I found myself constantly typing `foo, bar` during testing, so for ease of use I'd definitely try and keep it as-is (if possible).

**Comment by sampsyo** [comment]
OK, merged! We can at least see how people like this design. Thanks again! This will be awesome to have. :sparkles:

**Comment by raffomania** [comment]
Awesome! Thanks a lot, @tomjaspers!

**Pull request merged**
