### PR TITLE
Import only files which are not at the library

### PR DESCRIPTION
**Pull request by mried**
With this change, the importer will skip all files, which are already at the library. This is helpful if you import the whole library again to add files which are placed there after the last import. I made this the default behavior, but we could easily add an command line or configuration option to turn it on or off.

What do you think about it?

### CODE REVIEW

**Comment by mried** [comment]
Ah, some tests failed. The failed test are all testing the reimport of files so this is not a surprise. I didn't change them so far since I'm not sure if you really want the change I made.

**Comment by sampsyo** [comment]
Hmm… so the goal is to be able to do something like:

    $ beet imp /path/to/my/music

and only process stuff that's not already in the library? Maybe a simpler way to go about this would be to provide a new config option that just filters out *each file* that is in the library (using a direct `PathQuery` construction, btw, rather than a `path:` query string). This would just completely disable re-imports, which are definitely a feature we would want to keep enabled by default, for that specific situation.

Specifically, I'm a little worried about the additional complexity of skipping on a per-directory basis—this seems fragile, especially in situations where files are not organized by album (my singletons directory, for example).

**Comment by mried** [comment]
To clarify the intention of the change a bit more: I want to execute
```
beet imp /path/to/my/library
```
My `config.yaml` contains (beside a lot of other stuff, of course):
```
directory: /path/to/my/library
```
I want beets to add all files which were added there after the last import without trying to import the already imported files again.

OK, a `PathQuery` seems to be a good idea since it lowers the execution time a lot, I guess. Also the configuration option is ok for me.

But I'm not sure, if I got you right about the rest. The method I changed gets called with directory names in case of an album import and with file names in case of a singleton import. Maybe I just overlooked something?

**Comment by sampsyo** [comment]
> But I'm not sure, if I got you right about the rest. The method I changed gets called with directory names in case of an album import and with file names in case of a singleton import. Maybe I just overlooked something?

You've got it right—so we'd need to impose at a different point if we wanted to do a uniform per-file filter.

**Comment by mried** [comment]
Since I found a good way to implement all this using plugins (see #1463), I wonder if we still want this feature to be part of beets itself?
(You can find the plugin here: https://github.com/mried/beetsplug/blob/NotAgainPlugin/beetsplug/notagain.py)

**Comment by mried** [comment]
I'll close this since a solution could be found via a plugin.

**Pull request closed without merging**
