### PR TITLE
Add note about indenting config file sections

### PR DESCRIPTION
**Pull request by alphapapa**
Maybe this will help people avoid https://github.com/sampsyo/beets/issues/1125

### CODE REVIEW

**Comment by tomjaspers** [comment]
Maybe the comment could be generalized a bit to make clear that identation (as shown) is important for all subsections in the config?

**Comment by sampsyo** [comment]
Looking again, we already say that indentation needs to be spaces and not tabs at the top of the file, where the format is introduced. I think that's the right place for this note.

**Comment by sampsyo** [comment]
Actually, a note in the guide seems reasonable if it's not too long—I put one where the config format is introduced.

**Comment by alphapapa** [comment]
I'm glad you added a note to the getting started guide, because that was the point of this pull request: the guide was not sufficient on its own to avoid running into this bug, and I think most editors use tabs by default for indentation (even in Vim, Emacs, etc., the file format's settings may not be automatically set to use spaces).  And there's little point in having a "Getting Started" guide if a user still has to read the reference manual to do basic configuration.

However, I still recommend using a distinctive "NOTE" as I submitted, because this is a crucial detail that needs to stand out.  The error message gives no clue as to the problem ("configuration error: import must be a collection, not unicode").  And putting this note in parentheses at the end of a paragraph makes it easy to skim over when a new user is trying to quickly get set up so he can try out Beets.  It should probably be in a paragraph by itself, either bolded or with some other kind of distinctive "note" formatting.

Beets is for power-users, but even power-users prefer to get started quickly, with minimum effort, so little things like this are easy to miss.  A lot of potential users may be put off by an unhelpful error message on first-run after basic configuration, and may not have enough interest to put forth the effort to debug it.

**Comment by sampsyo** [comment]
Thank you for the suggestion. I'll continue to think about it, but there are other considerations here (everything that gets louder in text serves to drown something else out).

**Pull request closed without merging**
