### PR TITLE
Split date string using dashes

### LINKED ISSUE #1404: AttributeError when changing date tag
Hello! New beets user, and I am working on slowly importing my music into beets.

I can't actually change the date on any of the files that I've already imported. I started by trying to change the date on an album whose original release date was wrong on MusicBrainz. Here's the command I used:

beet -v modify The Autumn Effect date="2005-08-16"

and the output: https://gist.github.com/dirtdigger/aea6c0c97d5bfbae37ac

I tried rolling back to 1.3.10 in case it was something new, but the same thing happened there too. It doesn't just happen with that album, it's happened to any album that I try to change the date on, and it happens on both flac and mp3 albums. This also happens when I just try to change the date separately.

System information: beets 1.3.11, Arch Linux

Any help would be appreciated. Thanks :-)

### PR DESCRIPTION
**Pull request by multikatt**
Should resolve #1404

### CODE REVIEW

**Comment by brunal** [comment]
The tests are failing. I suspect date should be a datetime.datetime object but in #1404 for an unknown reason it was not. This is what should be solved.

**Comment by multikatt** [comment]
Sorry about that, should be better now.
But this might be the wrong way to resolve this.

**Comment by brunal** [comment]
I think so: it's fixing the symptom and not the problem: "date" is not in _fields or _types of Item and therefore does not get converted, but can be set.

**Comment by sampsyo** [comment]
Agreed: thanks for pointing this direction out, but I think we need to fix this in a different (pre-MediaFile) way.

**Pull request closed without merging**
