### PR TITLE
Discogs: change album artist to musicbrainz naming

### PR DESCRIPTION
**Pull request by kooimens**
Just a simple config option to change 'various' album artist to the one that MusicBrainz uses: Various Artists. For the purpose of having one V.A. album artist in your library.

### CODE REVIEW

**Comment by kooimens** [comment]
Not really sure how to name the new config option. Maybe 'musicbrainz_va' is a better one?

**Comment by sampsyo** [comment]
Cool. How about just a "various_name" option, which is set to the string "Various Artists" by default?

**Comment by kooimens** [comment]
I agree! But shouldn't we set it to "various" as a default, since that's the one discogs is using to name it's va albums?

**Comment by sampsyo** [comment]
Well, unless we want to change the default behavior to be more uniform. I would guess most people would want that (right?).

**Comment by kooimens** [comment]
Yeah true! I think this should do the job.

**Comment by sampsyo** [comment]
Looks great. Pending a few things, we're ready to merge:

* Document the option.
* Add a note about the behavior change (and the reason) to the changelog.
* Travis has one style nitpick.

**Comment by kooimens** [comment]
Done. Is there a way how I can avoid those conflicts in future?

**Comment by sampsyo** [comment]
You can resolve the conflicts by checking out your branch and doing a `git merge master`.

**Comment by sampsyo** [comment]
All merged up! Thank you! :sparkles:

**Comment by m-urban** [comment]
Shouldn't we make this a global option? I would like to control this for MusicBrainz as well…

**Pull request merged**
