### PR TITLE
Fix path query case sensitivity

### LINKED ISSUE #1165: Path queries are case-insensitive
I have two albums with the same name except for 1 difference: 

/media/bb/audio/jazz/Sinatra/In the Wee Wee Hours
/media/bb/adio/jazz/Sinatra/In The Wee Wee Hours

the difference is just a lowercase/uppercase (t/T)

when using the command
beet rm /media/bb/audio:jazz/Sinatra/In the Wee Wee Hours (or The Wee Wee)
beet asks me if I want to delete both of the albums
I checked and even with 
beet ls /media/bb/audio:jazz/Sinatra/In the Wee Wee Hours (or The Wee Wee)
I get both the albums.

Should beet not differentiate between lower/uppercase?

### PR DESCRIPTION
**Pull request by brunal**
PathQuery uses LIKE on Windows and instr() = 1 on UNIX.

Fix #1165.

### CODE REVIEW

**Comment by brunal** [comment]
Problem `instr()` is only available on [SQLite 3.7.15+](http://www.sqlite.org/changes.html) and [Debian Wheezy uses 3.7.13](https://packages.debian.org/search?keywords=sqlite3). Solutions:

- use a pragma as initially suggested
- use [a hack with `replace()`](http://stackoverflow.com/a/16180907) instead
- wait for Jessie to be the new stable (maybe in ~2 months)

**Comment by sampsyo** [comment]
Ack; that's too bad. The replace hack is not too dirty—let's do that for now, with a comment to remind us to switch to the real construct when we can.

**Comment by brunal** [comment]
`replace()` did not exactly meet our needs - checking the prefix. So instead I went with `substr(field, 1, len(dir_blob)) = dir_blog`.

This works **but** I'm 90% sure it fails with non-ascii characters. So... not ready to merge yet.

**Comment by sampsyo** [comment]
Dang! Get your string-manipulation act together, SQLite. :smiley:

**Comment by brunal** [comment]
As mentioned on IRC & in a commit message, a query is internally unicode, and there forbids any non-utf8 code point. Therefore a path query may not contain such characters. I added a simple test with an utf8 character.

**Comment by sampsyo** [comment]
Hey, thanks for your patience—I've been in the midst of constant travel for a few weeks, so my reviewing speed has been especially low.

This looks like the right direction. Can we roll back the `InvalidQueryError`s for un-decodable strings, though? I think we should instead start considering it a *programming* error (not a user error) if the argument to `parse_query_string` is bytes rather than Unicode. So we can just `assert is instance(s, unicode)` inside that function and take out the special bytes handling in `InvalidQueryError`.

**Comment by sampsyo** [comment]
As a much more minor secondary comment: I'd probably have gone for a `case_sensitive` flag on `PathQuery` for testability, with that perhaps being set according to `platform` by default but overridable for testing.

**Comment by brunal** [comment]
Good points! Here it is. I test both the behaviour by setting `case_sensitive` and the behaviour picked depending on the platform.

**Comment by sampsyo** [comment]
Awesome! Thanks again! All merged.

**Pull request merged**
