### PR TITLE
Embedart: fails on some jpegs because imghdr doesn't recognize the mimetype

### PR DESCRIPTION
**Pull request by nathdwek**
This errors pops up
```
embedart: Embedding album art into Queen - Live at Wembley ’86

embedart: not embedding image of unsupported type: image/x-None
```
with [this cover](http://i.imgur.com/b8TPrsC.jpg) (found by beets-fetchart).

This is due to [this issue](http://bugs.python.org/issue16512). Fortunately, `imghdr` provides the list `imghdr.tests` to add extra mimetype tests. I added a test which identifies jpeg files based on their magic bytes, which is the method used by `file`.

This is my first time contributing to beets, so I think some code style guidance is probably needed (mainly regarding the modification of `imghdr.tests`, which should only happen once). I also absolutely need some help with adding the right tests. There is some testing code in this PR, which is very naively based on the rest of `test_mediafile.py`, but the test doesn't fail without the patch, and I think it actually never runs. I should probably also find/build a smaller cover which can only be recognized based on the magic bytes.

### CODE REVIEW

**Comment by nathdwek** [comment]
I added a commit to fix the code style issues.

**Comment by sampsyo** [comment]
Awesome! Thanks for sorting this out. Looks great so far.

* I think the test belongs in a standalone test function, probably in the simpler `test_mediafile_edge.py`. The test can just call `_image_mime_type()` directly rather than using the automated test-battery machinery. Does that make sense?
* I would love to avoid modifying `imghdr.tests` is possible. Could we just run your new magic-number check ourselves if `imghdr` gives us None? (Avoiding changes to global state help make things more predictable down the road.)
* And finally, just to check: do you have reason to believe this check is fairly precise, i.e., there aren't a bunch of other formats that happen to use the same magic number? A link to the `file` policy would totally suffice.

**Comment by nathdwek** [comment]
*I'll have a look at `test_mediafile_edge.py` and see if I can get really started with tests without any external indication.
*I also felt kinda uncomfortable modifying `imghdr.tests` like that but it had the advantage of really being a "pluggable" solution. I'll look into alternatives.
*https://github.com/file/file/blob/master/magic/Magdir/jpeg#L12

**Comment by nathdwek** [comment]
I added a commit re:testing

**Comment by sampsyo** [comment]
Nice! The test looks great.

Would you mind adding a comment to the code with that link? Could help us stay less confused later on. :smiley:

**Comment by nathdwek** [comment]
I added two commits with a more elegant implementation which doesn't require to modify `imghdr.tests` and also comments for the test.

Should I try to build a smaller image which fits the edge case or is the 1000x1000 image acceptable in the test ressources?

**Comment by sampsyo** [comment]
This is looking great. Thanks for the extra comments.

A smaller image would be wonderful if it's not too difficult -- it seems a little suboptimal to add a 0.5 MB file to the beets distribution for just one test. (And avoiding copyrighted images is also a plus.)

**Comment by nathdwek** [comment]
Yeah I don't know I never tried but I guess it shouldn't be too difficult :)

**Comment by nathdwek** [comment]
I added a commit with a smaller test image.

**Comment by nathdwek** [comment]
Do I need to do anything else before this can be merged?

**Comment by sampsyo** [comment]
Nope, I was just being slow. Thanks for your patience.

**Comment by sampsyo** [comment]
All merged up! Thank you again! :sparkles:

**Comment by nathdwek** [comment]
Thank you very much for your responsiveness :smiley:

**Pull request merged**
