### PR TITLE
Fix a crash when extracting album art

### PR DESCRIPTION
**Pull request by mried**
The crash happened when the album path contains non ascii characters (like äöü). I'm not sure if the solution I implemented is the best way to get around this...

### CODE REVIEW

**Comment by sampsyo** [comment]
Thanks for catching this bug, and for including a test!

I have two comments on the fix:
* To make Unicode errors due to inconsistency go away, there are two choices: lift everything to Unicode or lower everything to bytes. It looks like you've chosen the former, but the standard in beets is the latter: paths should always be byte strings. Can you check whether this will work if you instead just encode `filename` to bytes and then combine it with `album.path` as it is?
* I think this is a regression from unicode_literals that was not present in the previous release, so we don't actually need a Changelog entry.

**Comment by mried** [comment]
Sorry for the delay. I changed as you suggested (hopefully :wink:) and it's still working as expected. I'm a bit unsure about the way I did the conversion: I used the `bytestring_path` helper method of the `util` module.

**Comment by sampsyo** [comment]
Looks great; thanks! If you feel like it, there's now a `a = a + b` that could go back to being `a += b`, but that is non-urgent.

**Comment by sampsyo** [comment]
Oops! I missed that something is wrong on Py26: https://travis-ci.org/sampsyo/beets/jobs/51269255

Can you please look into the test failure? I'm not totally sure what's up with it...

**Comment by mried** [comment]
Hmm, that's strange. If you look at https://travis-ci.org/sampsyo/beets/builds/51265874, everything is fine. The only thing I changed with the second commit is the changelog. I'd guess, this should not break the test :smile:.
Do you (or anybody else) have a hint for me where to start to search for a solution?

**Comment by brunal** [comment]
There's definitely a random side to it:
- when I run it locally with tox it fails most of the time
- when I run it locally in a python 2.6 virtualenv it never seems to fail

Maybe it's concurrency-related?

**Comment by brunal** [comment]
Found: the art in image.mp3 is sometimes a png image →gives extracted.png, or a jpeg image → gives extracted.jpeg and the test fails.

**Comment by brunal** [comment]
```
$ ffprobe test/rsrc/image.mp3
[...]
    Stream #0:1: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 2x3 [SAR 72:72 DAR 2:3], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      title           : the artist
      comment         : Artist/performer
    Stream #0:2: Video: png, rgb24, 2x3 [SAR 2835:2835 DAR 2:3], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      title           : album cover
      comment         : Cover (front)
```

There are 2 images in this mp3, one png and one jpeg. MediaFile.art seems to pick one arbitrarily - and randomly on python 2.6.

Easy solutions for that test: 
* remove the jpeg stream from `image.mp3` (not really a good idea, and it would break some mediafile tests)
* expect `extracted.*` and not `.png` (probably sufficient for now)
* use another audio test file

This raises the problem of using `Mediafile.art` instead of `Mediafile.images` which would be better suited. However that raises several questions for the `embedart` plugin.

**Comment by mried** [comment]
Great! Thanks for you help! I tend to change the test so it expects `extracted.*`.

**Comment by mried** [comment]
I've changed the test case so it searches for `extracted.[png|jpeg|jpg]`.

**Pull request merged**
