### PR TITLE
Stop applying mp3gain directly to files. Fixes #1316

### LINKED ISSUE #1316: ReplayGain plugin with mp3gain backend is modifying source files.
If one enables the replaygain module using the mp3gain backend, the gain is being applied to the source files. Furthermore, the modifications are not reversible because the undo information is not being written to either source or destination files.

To reproduce:

Create this one-line ~/.config/beets/config.yaml:

```
plugins: replaygain
```

Per the [docs](http://beets.readthedocs.org/en/latest/plugins/replaygain.html#configuration), this will default to automatically analyze for replaygain, using the command backend.

Now, `beet import -A` a file. I use [this one](http://cdn.izrm.net/jaquer.net/projects/lala/lala.mp3), which has a `222912248f934554ec2eaaf1b191f938607ffbab` sha1sum.

The replaygain plugin calls mp3gain on the source with the "-r" parameter, which will apply the gain to the source file. Calling sha1sum on the source file after the import will show it has been modified.

Per the plugin docs, the gain should not be applied unless the `apply` config is set to `yes`, but even then, I don't believe that the intention was to modify at the source, was it?

By the way, the `apply` option was dropped from the plugin at 86ee30df0d177f9103a7c4e7489cbf06aaa62838. This is relatively easy to bring back, and I'd be happy to submit a PR fixing that omission, but the real problem is that even bringing that option/conditional check, the gain will still be applied to the source files.

### PR DESCRIPTION
**Pull request by jaquer**
Update docs to remove non-existent `apply` option.

### CODE REVIEW

**Comment by sampsyo** [comment]
Looks right to me! :sparkles: Could you please also add an entry to `docs/changelog.rst`?

**Comment by jaquer** [comment]
How's this?

**Comment by jaquer** [comment]
Wait, don't merge yet... now I'm bugged about `is_album` not being used at all.

**Comment by sampsyo** [comment]
OK, looks right to me! Sorry for the delay; merging now. :sparkles:

**Pull request merged**
