### PR TITLE
Fix typos

### LINKED ISSUE #1802: Typos in variables, methods & options
Here are some typos I've noticed:

https://github.com/sampsyo/beets/blob/master/beets/ui/commands.py#L443 `def _summary_judment(rec):` should be `def _summary_judgment(rec):`

https://github.com/sampsyo/beets/blob/master/beetsplug/play.py#L44 ` 'warning_treshold': 100,` should be ` 'warning_threshold': 100,`

I'll submit a PR to fix them soon.

### PR DESCRIPTION
**Pull request by JesseWeinstein**
Fixes #1802

### CODE REVIEW

**Comment by nathdwek** [comment]
The test fail is on me. I pushed a fix to /sampsyo/beets/tree/fix-typos . (Sorry)

@sampsyo : Opinions on how we should handle the typo in a configuration key?

**Comment by JesseWeinstein** [comment]
I think we should support the both, although probably have typo-ed version un-documented.

**Comment by nathdwek** [comment]
Yeah from a semver point of view that would make the most sense. I'm on it.

**Comment by nathdwek** [comment]
I pushed the code for backwards compatiblity. We just need tests and changelog before merging. I'll try to write the tests for the backwards compatibility of play asap, but I doubt I'll have the time to do it today.

**Comment by JesseWeinstein** [comment]
I've added a test; we just need a changelog entry.

**Comment by nathdwek** [comment]
You can merge from the fix-typos in the main repo and then I'll merge into master! :sunny:

**Pull request merged**
