### PR TITLE
Ipfs plugin

### PR DESCRIPTION
**Pull request by multikatt**
http://ipfs.io or https://github.com/ipfs/go-ipfs is a global, versioned, peer-to-peer filesystem.
This plugin is so far extremely rough, but it adds the option to add or get albums from ipfs.
So if i have an album in my library I can do
```beets ipfs -a [query]```
This will return individual hashes for all the albums files as well as a hash for the whole album.
I can then, in another library without this album, run
```beets ipfs -g [hash]```
and the album will be downloaded from ipfs and imported to the library.

Again, this is a very rough demo, so it's not merge:able yet. But i'd be interesting to hear what you think.

### CODE REVIEW

**Comment by sampsyo** [comment]
Wow! This is a very cool project. It's quite speculative, but that means it's definitely worth exploring.

So I know where you're going: Is there anything else you'd like the plugin to do? Importing from and exporting the music itself to the DFS seems good, but—for example—are you interested in storing indices of music there?

**Comment by multikatt** [comment]
Primarily this would be for sharing between friends. Instead of zipping and mailing the album over, then the friend has to import it into beets I can just send them the hash.

**Comment by sampsyo** [comment]
Very cool. I wonder how challenging it would be to be able to `beet ls` your friends library from ipfs too.

**Comment by multikatt** [comment]
That sounds possible. The hashes could be stored in the beets database and that database could be exported as json or something and added to ipfs. You could then give that json hash to your friend. That database should then be possible to use for ls and similiar.

**Comment by multikatt** [comment]
Now the steps to use this plugin is something like:
```
beet ipfs -a artist:tom waits # add all tom waits albums to ipfs. Store those hashes in the local library database
beet ipfs -p # publish a copy of the local library to ipfs, only for albums/items that has ipfs records in the db
# on a different host/instance of beets:
beet ipfs -i [hash returned from above -p] # import remote library, save in $lib/remotes
beet ipfs -l artist:tom waits # query all imported libraries, list results
beet ipfs -g artist:tom waits # query imported libraries, download the matching hashes from ipfs and import them to local library
```

Its still pretty bulky but it seems to be working rather well. I really dont like the -l or --list flag and would rather be able to do ```beet ls``` in some way but i can't think of a good syntax for using the non-local libraries nor a good way to implement it. Extending the query, [from plugins doc] (https://beets.readthedocs.org/en/latest/dev/plugins.html#extend-the-query-syntax), I guess should work somehow but I cannot figure out how to do it yet.

Tests remain to be written too.

**Comment by sampsyo** [comment]
Very neat; this looks like it's getting quite useful.

One design we considered a long time ago (and never implemented) was providing different implementations of the Library interface. Specifically, we used to have a Library that reflected the database on an iPod (back when we all had iPods) so you could list and manipulate music on your device using the same commands as your main beets library. Maybe this approach would be worth revisiting in this context—some way to make interaction with the IPFS catalog transparent.

**Comment by multikatt** [comment]
This plugin seems to be working rather well now. Here's the hash for a small three album library (on creative commons licence via Jamendo) QmWgeJoezjo8Y1PP7KXmAkAKVnsiubAydzFWSrgvcrsY76 .
I'd be really happy if someone would try it out.

This pull request has become rather long though, I like making many smaller commits. Maybe I should rebase?

@sampsyo is there any more documentation on the separate libraries you mentioned earlier? The plugin is so far still using the above syntax, which has kinda grown on me and doesn't feel as awkward anymore. But a nice transparent syntax would be cool though.

**Comment by sampsyo** [comment]
This is looking amazing! Thank you so much for your patience while I got caught up with the beets backlog.

I think we should merge this as-is. I'm sure it will continue to evolve, but this is already useful in its current state. And the set of commands is clearly complete. (And I don't mind the long commit history.)

There's not really any documentation on that deal with alternate Library implementations, and it would definitely be a big hacking job. Let's leave it for the future.

**Pull request merged**
