### PR TITLE
  Thread safe logging level adjustment, revisited

### PR DESCRIPTION
**Pull request by brunal**
This is another approach to the remaining logging issues (see #1320 and #1244). This supersedes PR #1366, **however this drops Python 2.6 support**. Indeed:
- it relies on `logging.Logger.level` being a property to a thread-local attribute
- properties do not work on python 2.6
- `logging.Logger` is an old-style class in python 2.6
- it cannot be made a new-style class because we dynamically patch the type of loggers to replace the logging manager (non-existent on python2.6)

Solutions include:
- dropping python 2.6 support (modification of tox.ini required)
- (just thought of it) override setLevel() instead of setting the level.

### CODE REVIEW

**Comment by sampsyo** [comment]
OK, let's do it—seems like a reasonable time to drop 2.6. We'll also need to change `setup.py` and the installation docs to reflect the new minimum.

Beyond that, this looks great. Please feel free to merge at will.

**Comment by brunal** [comment]
Done!

I removed a couple python 2.6-related hacks, is there any I've forgotten? I don't think that replacing `set([...])` with `{...}` or "{0}".format(...) with "{}".format(...) are worth it but dropping hacks definitely is.

**Comment by sampsyo** [comment]
Looks great. I see one last result for `ack -i py26`, but it's not remotely urgent (and not really even a hack).

**Comment by brunal** [comment]
Good point, fixed.

**Pull request merged**
