### PR TITLE
Support paths with non ASCII characters

### PR DESCRIPTION
**Pull request by raymondwanyoike**
Convert paths to UTF-8. See #1557

### CODE REVIEW

**Comment by sampsyo** [comment]
Thanks for the report and investigation. We actually need to go the other way: *encode* the library directory rather than *decoding* ancestor paths. This is because we don't know the filesystem encoding (it may not be UTF-8), so it's easier to go one direction than the other.

**Comment by sampsyo** [comment]
Hmm… I dug in a little bit to investigate this, and I actually wasn't able to reproduce the problem. Even with a bunch of Unicode in the directory and base filenames, `permissions` worked fine. Specifically, on my setup, both arguments to `dirs_in_library` are bytes (i.e., they have type `str`).

Are you seeing that the `library` argument has type `unicode`? If so, do you have anything strange about your setup that would cause that? The code for the `Library.__init__` constructor should force it to be a bytestring in all cases.

**Comment by raymondwanyoike** [comment]
Yup `library` is type `unicode`:

```python
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 36: ordinal not in range(128)
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /usr/lib/python2.7/site-packages/beetsplug/permissions.py(38)dirs_in_library()
-> if ancestor.startswith(library)][1:]
(Pdb) type(library)
<type 'unicode'>
```

Nothing special about the setup: Locale: `en_US.UTF-8`, Python: 2.7.9, Beets: 1.3.13, Plugins: `duplicates, embedart, fetchart, info, inline, lastgenre, lyrics, missing, permissions, scrub, web`

**Comment by sampsyo** [comment]
Truly bizarre. I have a couple more questions that might help get to the bottom of this:

- Does the test you modified fail on your system before without your fix applied?
- Any chance you could paste your full config? Or, perhaps, try turning off all other plugins to make sure they're not interfering?

**Comment by raymondwanyoike** [comment]
- No, the test passes, `python test_permissions.py`, but if I add unicode to `album` in `TestHelper.create_importer`, e.g. `\u30a2\u30eb\u30d0\u30e0`, then the test fails (without my fix).
- I cloned and tried this on a different machine (OSX), same test error with unicode added to `album` in `TestHelper.create_importer`.
- The `library` argument ALSO has type `unicode` in the test.

My config; *if it is* my config, what about the test generated config?

```yaml
---

library: ~/Music/dat/Music/Beets/.beets.db
directory: ~/Music/dat/Music/Beets

paths:
    default: $albumartist/$album%aunique{}/$disktrack $title
    comp: Compilations/$album%aunique{}/$disktrack $title

per_disc_numbering: yes

plugins:
    - duplicates
    - embedart
    - fetchart
    - info
    - inline
    - lastgenre
    - lyrics
    - missing
    - permissions
    - scrub
    - web

embedart:
    maxwidth: 500

fetchart:
    maxwidth: 500
    sources: itunes *

lyrics:
    auto: no

item_fields:
    disktrack: '"{0}-{1:02d}".format(disc, track) if disctotal > 1 else "{0:02d}".format(track)'
```

**Comment by raymondwanyoike** [comment]
Think I found the culprit. Comparing `permissions.py` in tags v1.3.13, and v1.3.14 (I have v1.3.13):

- v1.3.13 (https://github.com/sampsyo/beets/blob/9f2d58e47a99ac8e71e7c9b12c716f8bd59900f3/beetsplug/permissions.py#L87-L90):

    ```python
    # Adding directories to the directory chmod queue.
    dir_chmod_queue.update(
        dirs_in_library(config['directory'].get(),
                        path))
    ```

    `config['directory'].get()` returns type `unicode `

- v1.3.14 (https://github.com/sampsyo/beets/blob/ba15f945acd257057b519dc837d346a8d48298f8/beetsplug/permissions.py#L87-L90):

    ```python
    # Adding directories to the directory chmod queue.
    dir_chmod_queue.update(
        dirs_in_library(lib.directory,
                        path))
    ```

    `lib.directory` returns type `str`

**Comment by raymondwanyoike** [comment]
Well then, why is the latest (v1.3.14) `test_permissions.py` failing when unicode is added? :wink: https://github.com/sampsyo/beets/blob/ba15f945acd257057b519dc837d346a8d48298f8/test/test_permissions.py#L37-L60

**Comment by raymondwanyoike** [comment]
This issue's fixed, *but* there is one last test error when unicode is added to `album` in `TestHelper.create_importer`: 

```python
======================================================================
ERROR: test_import_converted (__main__.ImportConvertTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_convert.py", line 89, in test_import_converted
    self.assertFileTag(item.path, 'convert')
  File "test_convert.py", line 47, in assertFileTag
    u'{0} is not a file'.format(path))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 80: ordinal not in range(128)

----------------------------------------------------------------------
```

https://github.com/sampsyo/beets/blob/v1.3.14/test/test_convert.py#L86-L89

```python
def test_import_converted(self):
    self.importer.run()
    item = self.lib.items().get()
    self.assertFileTag(item.path, 'convert')
```

`item.path` is type `unicode`. Similar issue? Anyway, I removed the commit with unicode from this pull request. Thanks.

**Comment by sampsyo** [comment]
Aha—that looks like it was probably a harness issue. The path field should never contain Unicode (it's always stored as encoded bytes), so if the test harness manufactured an Item like that, then a failure would be expected.

Anyway, thanks for looking into this!

**Pull request merged**
