### PR TITLE
New tests for human readable values

### PR DESCRIPTION
**Pull request by pkess**
Here i added some tests for the output of human readable values.
Especially the test of human_bytes is written as it would success now. But is the implementation really correct?
As you see at https://en.wikipedia.org/wiki/Petabyte a Petabyte is 10^15 bytes and not 2^50 bytes as implemented.

### CODE REVIEW

**Comment by sampsyo** [comment]
Great! But yes indeed—it looks like the exponents in the original code are wrong. :cry: Would you mind fixing them too?

**Comment by pkess** [comment]
I will be happy to fix it, but which style do we want to use?
10^n xB
or 2^n xiB

**Comment by sampsyo** [comment]
Good question. Let's say XiB (i.e., powers of two) since that's closest to what we're doing (or thought we were doing) already.

**Comment by pkess** [comment]
So i think i fixed it now.
Feel free to merge it

**Comment by sampsyo** [comment]
Awesome. :sparkles: I'll hit the merge button now, but would you mind also adding a note to the changelog about the fix?

**Comment by pkess** [comment]
Done. Hope you enjoy it

**Comment by sampsyo** [comment]
Looks perfect.

**Pull request merged**
