### PR TITLE
fetchart: Use success coloring if album art is found

### PR DESCRIPTION
**Pull request by Somasis**
This changes the 'has album art' message to use the green color used for success. I just think it makes it easier on the eyes.

### CODE REVIEW

**Comment by sampsyo** [comment]
Hmm... I like the notion, but it's also currently useful to have the cases where beets actually did new work to find album art stand out in the log. If everything but failure looks green, this is harder to see. Maybe we should be using a different color?

**Comment by Somasis** [comment]
Blue? Yellow?

**Comment by sampsyo** [comment]
Good question; it's of course very subjective. :smiley: Maybe yellow, since we already use that for an intermediate state? Or `lightgray` since we sort of want it to fade into the background?

**Comment by Somasis** [comment]
How's that? `lightgray` (or, `text_highlight_minor`) sounded good to me.

**Comment by sampsyo** [comment]
Looks great! Thank you!

**Pull request merged**
