### PR TITLE
fix #1178, update docs to put asterisk in quotes

### LINKED ISSUE #1178: config: Star character in source lists can cause YAML syntax error
the `*` char is used in *sources* option of lyrics plugin as a shortcut for *all sources*

    lyrics:
        sources: * google 

(all sources with google in last position) gives : 

    configuration error: file /Users/flap/.config/beets/config-test.yaml could not be read: while scanning an alias
      in "/Users/flap/.config/beets/config-test.yaml", line 51, column 14
    expected alphabetic or numeric character, but found ' '
      in "/Users/flap/.config/beets/config-test.yaml", line 51, column 15

works as expected though with following notation : 

    lyrics:
        sources: ['*', 'google']

### PR DESCRIPTION
**Pull request by Kraymer**

### CODE REVIEW

**Comment by sampsyo** [comment]
Are we sure this will work? It seems to me like the string `"itunes '*'"` will create two elements in the source list, one of which is `"'*'"`, so the `sanitize_choices` function will see that element as not equal to `"*"`.

**Comment by sampsyo** [comment]
Perhaps the advice should just be that, if you have to start a source list with `*`, make sure to put the whole thing in quotes?

    >>> yaml.load('* foo')
    [horrible exception]
    >>> yaml.load('"* foo"')
    '* foo'

**Comment by Kraymer** [comment]
I've put the ``sources`` lists in quotes in the examples, so looking at the docs hints to the resolution, should someone be bitten by this bug.

You think it's ok? I'm somewhat reluctant to state the thing explicitely as it is not related to beets *per se* and concerns a tiny minority of users (who uses the star char).

**Comment by sampsyo** [comment]
Yeah, looks good. Let's see if anyone gets confused; we can expand the docs if so.

**Pull request closed without merging**
