### PR TITLE
[WIP] Refactor beets.ui.commands

### PR DESCRIPTION
**Pull request by pradyunsg**
This PR is meant to re-organize/split beets.ui.commands module into a package. This reorganization splits the commands up into separate (fairly) independent modules of the new beets.ui.commands package.

Before putting in more time into this, I just wanted to know what others and the project maintainer(s?) think of this idea. Also, I wanted to ask a few questions related to this:
 - what all should be imported back into `beets.ui.commands` to maintain reasonable backwards compatibility?

--------

TODO:

 - [x] Take a nicer approach for importing commands into beets.ui.commands (Handled in #1484)
 - [ ] Move TerminalInputSession out of beets.ui.commands
 - [ ] Refactor tests so that they don't use the old functions (that no longer exist). They should use command.func instead.  
       - May I also move the tests for commands into a sub-directory of the test directory?
       - Or rename them into test_command_*.py?
       - Or even move all tests for beets.ui into test/ui and for beets.ui.commands into test/ui/commands?

### CODE REVIEW

**Comment by sampsyo** [comment]
Interesting! Thank you for being interested in some refactoring.

I'm not 100% sure whether reorganizing `beets.ui.commands` into multiple modules is an improvement in legibility for me. With the (very significant!) exception of the importer CLI, the command functions are pretty short—which, for me, makes one big file with all of them pretty easy to navigate. Are there particular reasons that make many smaller files easier to deal with?

Maybe an alternative would be to just "break off" support for the `import` command, since it so overwhelmingly dominates the code there. We'd make a new module named `beets.ui.importer_ui` or `.import_cli` or `import_command` or something similar, but otherwise leave stuff in `beets.ui.commands`. Would that address the difficulties currently presented by one long file?

**Comment by pradyunsg** [comment]
Well, then we could possibly change the .funcs into command classes and move `TerminalImportSession` out into a separate file (underscore file?) which would then be imported and used by ImportCommand.func in that file?

The reason I'm sticking with the "Command" concept is that setting an attribute on an instantiated object is pretty hacky IMO. It's much nicer to override an abstract method. That's kind of what this re-factor should get rid of, I think. But yes, assigning func should still be valid (for backwards compatibility). It should really not be the standard approach.

PS: Running a command line editor?

**Comment by sampsyo** [comment]
Sure, moving the `TerminalImportSession` subclass to its own module makes a lot of sense to me—it's a clearly-defined unit that would work well on its own.

On command classes, though (an orthogonal refactoring): have you seen the effort around porting to Click? See #1484 for the latest. This should also resolve the (admittedly) ugly appearance of the subcommand setup for the old optparse machinery.

**Comment by sampsyo** [comment]
And yes, I'm a vim person.

**Comment by pradyunsg** [comment]
So, looks like just pulling `TerminalImportSession` out is what's this PR ends up doing. The other part of the refactor is handled by #1484. Correct?

**Comment by sampsyo** [comment]
Sounds like a good work list, but let's take it one step at a time: let's just do the separation of TerminalImportSession in this (or a new) PR, and then work on the tests next, since they're distinct tasks.

The granularity of the test depends very much on the individual test. For white-box integration tests, yes, calling the main entry point makes sense. For other cases, more like true *unit* tests, it can be clearer and less error-prone to call a specific function directly. So this is really case-by-case: sorry the answer isn't simpler!

**Comment by pradyunsg** [comment]
Sounds good...

**Comment by pradyunsg** [comment]
Force pushed...

**Comment by sampsyo** [comment]
Cool! Looks like some tests need to be synced up: https://travis-ci.org/sampsyo/beets/jobs/69293757

**Comment by pradyunsg** [comment]
Yeah! I'll do that part tomorrow, when I would positively get started on
the tests...

On 9:54pm, Thu, 2 Jul 2015 Adrian Sampson <notifications@github.com> wrote:

> Cool! Looks like some tests need to be synced up:
> https://travis-ci.org/sampsyo/beets/jobs/69293757
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sampsyo/beets/pull/1523#issuecomment-118084231>.
>
-- 
Pradyun S. Gedam

**Comment by pradyunsg** [comment]
I'm starting to wonder if this should wait a littile until we get the tests out of the bag, I'm making a new PR for the tests right now and I have a lot of ideas...

**Comment by untitaker** [comment]
I suspect that we'll have to refactor `beets.ui.commands` anyway for #1484. Perhaps these two PRs should be unified.

**Comment by pradyunsg** [comment]
Sounds good to me.

**Pull request closed without merging**
