### PR TITLE
Fix lastimport #1574 (LastFM API change)

### LINKED ISSUE #1574: lastimport: Unable to read page
Hi everyone,

Is anyone else having issues with lastimport at all?

```
lastimport: Fetching last.fm library for @mysticg
lastimport: Querying page #1...
lastimport: ERROR: unable to read page #1
lastimport: Retrying page #1... (1/3 retry)
lastimport: ERROR: unable to read page #1
lastimport: Retrying page #1... (2/3 retry)
lastimport: ERROR: unable to read page #1
lastimport: Retrying page #1... (3/3 retry)
lastimport: ... done!
lastimport: finished processing 1 song pages
lastimport: 0 unknown play-counts
lastimport: 0 play-counts imported
```

My config as per the manual is just

```
lastfm:
    user: mysticg
```

Any suggestions?  I'm wondering if it might be related to the Last.fm site updates?

### PR DESCRIPTION
**Pull request by LordSputnik**
Fixes #1574 by changing the API method from library.getTracks to user.getTopTracks, which returns similar information (mbid, artist, title, playcount).

Also, I've replaced the custom HTTP request (using requests) with the pylast library, which is already a dependency of lastgenre.

### CODE REVIEW

**Comment by sampsyo** [comment]
Truly awesome! Thanks for looking at this---I didn't know there was an alternative API endpoint we could use. :tada:

And thanks for updating the docs too!

It looks like the tests may need to be updated to sync with the new version. And we'll also need a changelog, after which this should be good to merge.

**Comment by LordSputnik** [comment]
Ah, looks like I have any error in the docs - will get that fixed and changelog done.

**Comment by sampsyo** [comment]
Perfect; thanks again! :sparkles:

**Comment by rjgould** [comment]
Thanks @LordSputnik

**Comment by petwri** [comment]
Thank you for fixing this. I am updating beets via pip, when will this fix be available there? It's still not working on the current version I have updated to.

**Comment by sampsyo** [comment]
As soon as we do a new release. If you need the fix sooner, you can consider running from source (as described in the FAQ).

**Pull request merged**
