### PR TITLE
Display clear error message when MusicBrainz is unreachable

### LINKED ISSUE #1190: Better error message when MusicBrainz is unreachable
A user [recently was confused by a terrible error message](https://botbot.me/freenode/beets/2014-12-28/?msg=28424335&page=1) when their DNS was misconfigured:

    Error: "caused by: <urlopen error [Errno -2] Name or service not known>" in
    release search with query blah blah blah...

It would be great to have this instead print "MusicBrainz not reachable" (maybe with more info in the verbose log).

### PR DESCRIPTION
**Pull request by tomjaspers**
E.g.:  `Error: MusicBrainz not reachable in get release by ID with query etc etc ...`

Catch musicbrainzngs.WebServiceError before the general musicbrainzngs.MusicBrainzError
Fix #1190

### CODE REVIEW

**Comment by sampsyo** [comment]
Great; thanks for getting to the bottom of this.

Can I suggest a slightly different fix that requires less duplicated code? Inside `MusicBrainzAPIError.__init__`, let's just do something like:

    if isinstance(reason, musicbrainzngs.WebServiceError):
        reason = 'MusicBrainz not reachable'

That is, we can centralize this check and string literal in one place if we move it to the exception constructor.

**Comment by tomjaspers** [comment]
Good suggestion; I knew there had to be a better solution than this.

**Comment by tomjaspers** [comment]
@sampsyo Good suggestion; I knew there had to be a better solution.

**Comment by sampsyo** [comment]
Merged! Thanks for taking care of this. :sparkles: That's two contributions in one week for you! A double thank-you is in order. :smiley:

**Pull request merged**
