### PR TITLE
Add debug log for plugin paths

### PR DESCRIPTION
**Pull request by guibog**
I needed this info when creating a plugin.

By the way, do you prefer small PRs like this one? Or more consequent ones (e.g. some more debug logs could be added, maybe better if I propose a bigger PR?)

### CODE REVIEW

**Comment by brunal** [comment]
Hi,
You should probably pass the paths through `util.displayable_path`.
Why do you need this? One can simply do `$ beet config` to get that information.

I am not the owner of the repo but PR size does not really matter, what's important is the global coherence: a PR should have only one goal & fulfil it.

**Comment by sampsyo** [comment]
I agree completely about PR size. A small one like this is fine if it's focused on a particular logical change.

And, yes, I have the same question: isn't this information directly visible in the configuration?

**Comment by guibog** [comment]
@brunal @sampsyo some advantages of adding pluginpath to debug:

1) With `beet config` I have a big dump of yaml, need to parse it, need to know which key is relevant.

2) With `beet config` I may get an unexpanded path like `pluginpath: [~/beets/newplugs]`, and maybe it expanded wrongly.

3) Adding a debug log also helps me make sure the pluginpath config is set and correctly so *before* I see the "plugin not found" error.

I would obviously not add this to info level log, but it seems to make sense in debug level log. But maybe `-v` should display info level, and -vv should display debug level.

(But obviously I don't care *that* much about the presence or absence of one debug log in beets. If you do not like this PR I'll just drop it.)

**Comment by sampsyo** [comment]
Seems fine; this is a perfectly reasonable explanation. I was just interested to hear how this came up.

Can you check that the strings are unicode and, if not, pass them through `displayable_path` for safe logging? The we can merge this up.

**Comment by guibog** [comment]
Hi @sampsyo I'm now using directly `displayable_path`. As these paths are mapped to `util.normpath` just above, it has already been cleaned through `syspath` and `bytestring_path`.

**Comment by sampsyo** [comment]
Thank you!

No worries about force pushing the new commit vs. the alternative; we strive to avoid having too many rules here.

**Pull request merged**
